### ISSUE TITLE
More informative editor error messages based on API response

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#499]
Currently, the user has no way of knowing what is wrong with the POSTed Hearing data.

Returning error message specific to the API response string (the name of the field for the error) should give the user a better idea of what is wrong.

**Comment by jonnetanninen** [comment]
This might be hard to implement well due to current error handling. Amount of these should already be minimal due to the validation done in the UI.

Would it be ok to just display the response message of the failed api call?  Otherwise I would need list of possible responses to be able to translate them.

**Comment by Rikuoja** [comment]
At first step, just display the error message of the API response in parentheses, after "Jokin meni pieleen". Then, if we get repeating ones, we can consider translating them.

Also, when an error box (red) as opposed to success box (green) is displayed, is it possible to make the box persistent? This way, the user can at least take a screen capture and/or copypaste the whole text to us, before closing the box with an (x). Don't know if such an error component exists already.

**Comment by jonnetanninen** [comment]
The current box can be made persistent which is then closable by clicking the box. Adding an x-button however is not possible :(
