### ISSUE TITLE
Addin subsection content text in Admin UI doesn't work

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#523]
The UI tells the user "Tallennus onnistui", but actually the subsection content text is not saved and not visible in the Hearing.

**Comment by Rikuoja** [comment]
The same problem encountered with the main section content field.

Apparently this is the `onBlur` problem, where trying to save changes directly after editing text means the changes are just forgotten.

This will definitely need to be fixed, because we have exasperated users trying to fix typos in their text and failing repeatedly.

**Comment by jonnetanninen** [comment]
I agree and there is two ways that I know how to solve this:

1. Easy & Fast way: We change the "Save" -button event from onMouseDown back to onClick. This causes the side effect of the button not working on first click (as that fires the onBlur on first click). This is definitely not optimal UX, but will be improvement at this point. Maybe could work as a fast but temporary solution?

2. Not so fast solution...: We refactor the form to save changes onChange instead of onBlur, how I think it should've been implemented in the first place. Unfortunately when I tested this, it caused performance issues when typing fast or continuously pressing backspace. To find out why this is will certainly take quite some time. One way to fix this performance issue could be to refactor the form to use redux-form, but that might lead to having to completely rewrite the editor logic...

**Comment by Rikuoja** [comment]
Well, this will need fixing ASAP, so let's go with option 1 first.
