### ISSUE TITLE
As a resident I want to be able to share a hearing in the social media.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#58]

**Comment by rambo** [comment]
This means (AFAIUnderstand) we have to have some URL that renders hearing in HTML as well (not just pure React.js Single Page App) for FB to crawl the OG tags for cover image & description.

Also we need to choose a service for aggregating various SoMe platforms to have "addthis" -style bar of options instead of bazillion different share-widgets for all the platforms users might want to use.

**Comment by akx** [comment]
Not hard to render the same view server-side for sharing if we don't want to go full isomorphic.

**Comment by rambo** [comment]
We probably do want to go full isomorphic due to for example #5, unless there is a simpler way to solve that as well ?

**Comment by itimo** [comment]
From original use case comments: "Includes adding Open Graph metadata to page."

**Comment by juyrjola** [comment]
Making an isomorphic app is generally a good idea. The main downside is that for each page load, the Express server needs to fetch the resource from the API before any HTML is returned to the browser. This adds a bit of latency and some extra load on the backend, but caching should alleviate both of these problems.

**Comment by joonasp** [comment]
At some point, do we want also to provide people a chance to share a specific comment to facebook? sharing their own comment (or someone else's for that matter), could make the shared post more interesting, provocative, etc.
