### ISSUE TITLE
As admin, I want to be able to add a process visualization in admin UI

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#611]
Al fields should be open-ended and have a character limit. Only one phase should be selectable as active.

Sketches: https://sketch.cloud/s/DE904/all/admin-ui/vaiheiden-lisays-2

https://sketch.cloud/s/DE904/all/admin-ui/vaiheiden-lisays

**Comment by Rikuoja** [comment]
Relevant backend issue at https://github.com/City-of-Helsinki/kerrokantasi/issues/269

**Comment by Rikuoja** [comment]
In addition to the sketch below, add a dropdown at "4. Prosessin vaiheet" above "Lisää vaihe" button that says "Valitse olemassaoleva projekti", with listing of all the projects in the backend projects endpoint.

This dropdown should populate the store with the phases in an existing project. Otherwise, create an empty project json when the user clicks "Lisää vaihe".

In both cases, the project id should be included in the JSON to be POSTed to the backend. Then, the backend will update the existing/new project phases accordingly.

**Comment by Rikuoja** [comment]
The "aktiivinen" checkbox indicates that the current Hearing belongs to that phase in the project.

**Comment by Rikuoja** [comment]
Project dropdown included: https://sketch.cloud/s/DE904/all/admin-ui/vaiheiden-lisays-projektilla

**Comment by Rikuoja** [comment]
Worst case scenario, if the Hearing has several languages: https://sketch.cloud/s/DE904/all/admin-ui/vaiheiden-lisays-2-kielet
